export { default as Header } from "./Header";
export { default as Footer } from "./Footer";
export { default as Feed } from "./Feed";
export { default as MovieCard } from "./MovieCard";
export { default as Posts } from "./Posts";
export { default as Tickets } from "./Tickets";
export { default as HeaderTitle } from "./HeaderTitle";
export { default as CarouselImage } from "./CarouselImage";
export { default as CustomeCard } from "./CustomeCard";
